global using FluentValidation.AspNetCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.IdentityModel.Tokens;
global using Morsley.UK.People.API.Common.Swagger;
global using Morsley.UK.People.API.Contracts.Requests;
global using Morsley.UK.People.API.Contracts.Responses;
global using Morsley.UK.People.API.Security.Models;
global using Morsley.UK.People.API.Security.Token;
global using Morsley.UK.People.Common;
global using Serilog;
global using Serilog.Events;
global using System.IdentityModel.Tokens.Jwt;
global using System.Reflection;
global using System.Security.Claims;
global using System.Text;
global using IAuthenticationService = Morsley.UK.People.API.Security.Interfaces.IAuthenticationService;
global using IAuthorizationService = Morsley.UK.People.API.Security.Interfaces.IAuthorizationService;
global using AuthenticationService = Morsley.UK.People.API.Security.Services.AuthenticationService;
global using AuthorizationService = Morsley.UK.People.API.Security.Services.AuthorizationService;
global using ILogger = Serilog.ILogger;
global using System;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Configuration;
