global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Morsley.UK.People.Application.Interfaces;
global using Morsley.UK.People.Caching.Contexts;
global using Morsley.UK.People.Caching.Interfaces;
global using Morsley.UK.People.Caching.Repositories;
global using Morsley.UK.People.Domain.Models;
global using Morsley.UK.People.Persistence.Configuration;
global using StackExchange.Redis;
