global using MongoDB.Driver;
global using Morsley.UK.People.Application.Events;
global using Morsley.UK.People.Application.Handlers;
global using Morsley.UK.People.Application.Interfaces;
global using Morsley.UK.People.Application.IoC;
global using Morsley.UK.People.Domain.Models;
global using Morsley.UK.People.Messaging;
global using Morsley.UK.People.Persistence.IoC;
global using Morsley.UK.People.Synchronizer;
global using Serilog;
global using Serilog.Events;
global using System.Diagnostics;
global using ILogger = Serilog.ILogger;
